# Generated by Django 4.1.1 on 2022-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('ganre', models.CharField(max_length=255)),
            ],
        ),
    ]
